// GENERATED-file harvester: pulls public GitHub data into src/github.gen.ts.
// Deliberately opinion-free — hiding / featuring / rewrites live in content.ts
// so policy changes never require re-running this.
// Free forever: GitHub public API (+ optional free GITHUB_TOKEN for headroom).
import { readFile, writeFile } from "node:fs/promises";

const OWNER = "dahalujwal1000";
const OUT = new URL("../src/github.gen.ts", import.meta.url);
const README_CHARS = 1200; // README digest cap (bot reads the front of it)

const headers = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  "User-Agent": "portfolio-sync",
};
if (process.env.GITHUB_TOKEN) {
  headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
}

async function api(path) {
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) throw new Error(`${path} → HTTP ${res.status}`);
  return res.json();
}

function stripMarkdown(md) {
  return md
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/^\s{0,3}#{1,6}\s+/gm, "")
    .replace(/[*_`~>|]/g, "")
    .replace(/\r/g, "")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{2,}/g, "\n")
    .trim();
}

function digest(md) {
  const text = stripMarkdown(md);
  if (text.length <= README_CHARS) return text;
  const cut = text.slice(0, README_CHARS);
  return `${cut.slice(0, Math.max(cut.lastIndexOf(" "), 400)).trim()} …`;
}

async function run() {
  let repos;
  try {
    repos = await api(`/users/${OWNER}/repos?per_page=100&sort=pushed`);
    if (!Array.isArray(repos)) throw new Error("unexpected response");
  } catch (err) {
    // the site must never break over a sync hiccup — keep the last snapshot
    try {
      await readFile(OUT);
      console.warn(`[sync] GitHub unreachable (${err.message}) — keeping existing github.gen.ts`);
      return;
    } catch {
      console.warn("[sync] GitHub unreachable and no snapshot yet — writing empty set");
      repos = [];
    }
  }

  const kept = repos.filter((r) => !r.fork && !r.archived);
  const out = [];
  for (const r of kept) {
    let readMe = "";
    try {
      const rm = await api(`/repos/${r.full_name}/readme`);
      readMe = digest(Buffer.from(rm.content ?? "", "base64").toString("utf8"));
    } catch {
      /* no readme — the bot will use description/topics only */
    }
    out.push({
      name: r.name,
      description: r.description ?? "",
      topics: r.topics ?? [],
      language: r.language ?? "",
      stars: r.stargazers_count ?? 0,
      pushedAt: r.pushed_at ?? "",
      url: r.html_url,
      homepage: r.homepage ?? "",
      readMe,
    });
  }

  const file = `// GENERATED by scripts/sync-github.mjs — do not edit by hand.
// Regenerate anytime: npm run sync (also runs automatically before every build).
// Data: public GitHub repos for ${OWNER} (forks & archived skipped).

export type GithubRepo = {
  name: string;
  description: string;
  topics: string[];
  language: string;
  stars: number;
  pushedAt: string;
  url: string;
  homepage: string;
  readMe: string;
};

export const githubRepos: GithubRepo[] = ${JSON.stringify(out, null, 2)};

export const githubSyncedAt = ${JSON.stringify(new Date().toISOString())};
`;
  await writeFile(OUT, file);
  console.log(`[sync] wrote ${out.length} repo(s) → src/github.gen.ts`);
}

run();