// GENERATED by scripts/sync-github.mjs — do not edit by hand.
// Regenerate anytime: npm run sync (also runs automatically before every build).
// Data: public GitHub repos for dahalujwal1000 (forks & archived skipped).

export type GithubRepo = {
  name: string;
  description: string;
  topics: string[];
  language: string;
  stars: number;
  pushedAt: string;
  url: string;
  homepage: string;
  readMe: string;
};

export const githubRepos: GithubRepo[] = [
  {
    "name": "norvic-hospital",
    "description": "a hospital website with full froentend and backend",
    "topics": [],
    "language": "JavaScript",
    "stars": 2,
    "pushedAt": "2026-09-04T09:00:24Z",
    "url": "https://github.com/dahalujwal1000/norvic-hospital",
    "homepage": "",
    "readMe": "Norvic Hospital Website\nThis is a React + Vite template for the Norvic International Hospital website.\nProject Structure\n- src/components – Reusable components (Navbar, Footer, etc.)\n- src/pages – Page components (HomePage, AboutPage, ServicesPage, DoctorsPage, ContactPage)\n- src/css – Global styles and design tokens\n- public – Static assets\nFooter Design\nThe footer matches the homepage’s clean, light‑theme look while providing essential hospital information in a clear three‑column layout.\nLayout (desktop → tablet → mobile)\n1. Quick Links – Navigation to all main site pages plus Emergency, International Patients, Health Packages, Medical Insurance, Patient Portal.\n2. Contact Information – Address, phone, email, 24/7 Emergency line, with icons and social‑media links.\n3. Subscribe for Updates – Simple email signup form for health tips and hospital news.\nBelow the columns is a dark‑topped copyright bar with the year and site link.\nVisual Consistency\n- Uses the same CSS variables (--color-bg-secondary, --color-text-primary, --color-primary, etc.) and utility‑class spacing (px-4 sm:px-6 lg:px-8, space-y-, grid, flex) as the rest of the site.\n- Links, icons, and buttons have hover/focus …"
  },
  {
    "name": "Notes_SaaS",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-03T17:25:17Z",
    "url": "https://github.com/dahalujwal1000/Notes_SaaS",
    "homepage": "",
    "readMe": "Notes SaaS API\nA production-style Notes CRUD backend with JWT authentication — built as a portfolio project to demonstrate real backend skills: auth, relational DB design, REST design, and security fundamentals.\n 🔗 Live app: https://notes-saas-001-final.onrender.com — the full Notion-style UI, deployed on Render (free tier; the first request after 15 min of inactivity may take 50 s while the service wakes up). API reference: /docs.\nFeatures\n- AI assistant (new) — a sidebar chat (\"Agents & tools → AI Assistant\") powered by a free LLM (Google Gemini, Groq or Mistral, no credit card; an offline mock assistant runs when no key is configured). It can read your tasks/notes/events and create, move, rename and delete via tool calling — the LLM never touches the database, every call is validated and scoped to your account, deletes require an explicit Confirm/Cancel step, all actions are audited (aiactions table), and chat is rate-limited per user. Config: AIPROVIDER / AIAPIKEY / MISTRALAPIKEY / AIMODEL / AIENABLED in .env — see .env.example.\n- SaaS workspace dashboard (new) — collapsible #FAFAFA sidebar with Upcoming events (add events with name/description/date; shows title, date + …"
  },
  {
    "name": "Project_zero_delay",
    "description": "",
    "topics": [],
    "language": "JavaScript",
    "stars": 0,
    "pushedAt": "2026-09-01T17:56:47Z",
    "url": "https://github.com/dahalujwal1000/Project_zero_delay",
    "homepage": "",
    "readMe": "Nepal Gamer Voice Chat\nA lightweight, low-latency voice chat application designed specifically for Nepal gamers to beat Discord in performance and accessibility.\n🔄 Recent Updates\n- Server port auto-discovery. The signaling server scans upward from its preferred port (default 3000) and writes the chosen port to server/.resolved-port. The frontend calls GET /port to learn which port to connect to. No more EADDRINUSE crashes when another process is squatting on the default.\n- Static frontend dev server. npm run frontend (or npm run dev) serves src/ on port 5173 (or the next free port). The Tauri wrapper is still supported but no longer required for local development.\n- Authentication flow. registerEmail accepts a username and writes a users/{uid} doc to Firestore. The UI reads it back so the bottom-bar username is the chosen name, not an email prefix.\n- Icon set. Replaced the Font Awesome kit placeholder (which was 403ing) with inline SVG icons for mic / headphones / cog / close.\n- Loading overlay. Clears as soon as app.js parses, so Firebase init errors don't strand the user on a spinner.\n🎯 Features\n- Ultra-low latency voice chat ( /port → {\"port\": }\nGET http://localhost: /health …"
  },
  {
    "name": "My_Portfolio",
    "description": "",
    "topics": [],
    "language": "TypeScript",
    "stars": 0,
    "pushedAt": "2026-08-31T17:42:37Z",
    "url": "https://github.com/dahalujwal1000/My_Portfolio",
    "homepage": "",
    "readMe": "My Portfolio\n Portfolio site — dark terminal/CLI aesthetic, inspired by akkila.dev.\nStack\n- React 18 + TypeScript + Vite\n- Plain CSS (CSS custom properties) — no UI framework\n- Google Fonts → JetBrains Mono\n- Deploy target: Vercel (static, free)\nQuick start\nbash\nnpm install\nnpm run dev # local dev → http://localhost:5173\nnpm run build # type-check + production build (dist/)\nnpm run preview # preview the production build\nCustomize\nAll site content (name, links, projects, terminal answers) lives in a single file:\nsrc/content.ts <- edit everything here\nProject structure\nsrc/\n content.ts <- edit everything here\n App.tsx\n main.tsx\n index.css\n hooks/useReveal.ts <- scroll-reveal (IntersectionObserver)\n components/\n DotBackground.tsx <- interactive cursor-repel dot grid (full-page canvas)\n Nav.tsx\n Hero.tsx\n Terminal.tsx <- interactive /ask-me.sh widget\n Projects.tsx\n Contact.tsx\n Footer.tsx\nRoadmap\n- [ ] Replace placeholder projects with real work\n- [ ] Wire the contact form to a backend (Formspree / Resend)\n- [ ] Optional 3D hero object (Three.js / React Three Fiber)"
  },
  {
    "name": "-nepal-gamer-voice_ZERO_DELAY",
    "description": " lightweight, low-latency voice chat application designed specifically for Nepal gamers to beat Discord in performance and accessibility.",
    "topics": [],
    "language": "",
    "stars": 0,
    "pushedAt": "2026-08-01T22:04:54Z",
    "url": "https://github.com/dahalujwal1000/-nepal-gamer-voice_ZERO_DELAY",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "Wheather_mobile_app",
    "description": "",
    "topics": [],
    "language": "Dart",
    "stars": 0,
    "pushedAt": "2026-08-01T04:28:12Z",
    "url": "https://github.com/dahalujwal1000/Wheather_mobile_app",
    "homepage": "",
    "readMe": "Wheathermobileapp\nWheathermobileapp"
  },
  {
    "name": "Wheather_App",
    "description": "A real time wheather showing with api ",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-07-24T08:24:58Z",
    "url": "https://github.com/dahalujwal1000/Wheather_App",
    "homepage": "",
    "readMe": "Weather App - Django Project\nA simple weather application built with Django that fetches real-time weather data from the OpenWeatherMap API.\nFeatures\n- Current weather information for any city\n- Temperature, humidity, pressure, and wind speed\n- Weather description and icon\n- Responsive design that works on mobile and desktop\n- Clean and modern UI with CSS animations\n- Error handling for invalid cities or API issues\n- Built with Django backend and vanilla JavaScript frontend\nSetup Instructions\n1. Clone or download this repository\n2. Install dependencies\nbash\npip install -r requirements.txt\n3. Get an API key from OpenWeatherMap\n- Go to OpenWeatherMap\n- Sign up for a free account\n- Get your API key from the API keys section\n4. Create a .env file\nCreate a .env file in the project root directory (same folder as manage.py) with the following content:\nOPENWEATHERAPIKEY=youractualapikeyhere\nReplace youractualapikeyhere with the actual API key you obtained from OpenWeatherMap.\n5. Run the development server\nbash\npython manage.py runserver\n6. Visit the application\nOpen your web browser and go to: http://127.0.0.1:8000/\nHow to Use\n1. Enter a city name in the input field (default is London)\n2. …"
  },
  {
    "name": "portfolio",
    "description": "",
    "topics": [],
    "language": "TypeScript",
    "stars": 0,
    "pushedAt": "2026-07-22T10:58:39Z",
    "url": "https://github.com/dahalujwal1000/portfolio",
    "homepage": "",
    "readMe": "React + Vite\nThis template provides a minimal setup to get React working in Vite with HMR and some Oxlint rules.\nCurrently, two official plugins are available:\n- @vitejs/plugin-react uses Oxc\n- @vitejs/plugin-react-swc uses SWC\nReact Compiler\nThe React Compiler is not enabled on this template because of its impact on dev & build performances. To add it, see this documentation.\nExpanding the Oxlint configuration\nIf you are developing a production application, we recommend using TypeScript with type-aware lint rules enabled. Check out the TS template for information on how to integrate TypeScript and Oxlint's TypeScript related rules in your project."
  },
  {
    "name": "URL_Shortner",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 1,
    "pushedAt": "2026-07-20T12:07:01Z",
    "url": "https://github.com/dahalujwal1000/URL_Shortner",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "dahalujwal1000",
    "description": "",
    "topics": [],
    "language": "",
    "stars": 1,
    "pushedAt": "2026-07-18T10:51:06Z",
    "url": "https://github.com/dahalujwal1000/dahalujwal1000",
    "homepage": "",
    "readMe": "💫 About Me:\nDesigning wireframing Froentend HTML CSS JS\n🌐 Socials:\n \n💻 Tech Stack:\n \n📊 GitHub Stats:\n \n \n \n---"
  },
  {
    "name": "E-commerce",
    "description": "",
    "topics": [],
    "language": "HTML",
    "stars": 0,
    "pushedAt": "2026-07-18T02:50:26Z",
    "url": "https://github.com/dahalujwal1000/E-commerce",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "College-Website",
    "description": "",
    "topics": [],
    "language": "HTML",
    "stars": 0,
    "pushedAt": "2026-07-18T01:55:59Z",
    "url": "https://github.com/dahalujwal1000/College-Website",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "hckathon_practice",
    "description": "",
    "topics": [],
    "language": "",
    "stars": 0,
    "pushedAt": "2026-07-16T05:37:18Z",
    "url": "https://github.com/dahalujwal1000/hckathon_practice",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "new_practice",
    "description": "",
    "topics": [],
    "language": "CSS",
    "stars": 0,
    "pushedAt": "2026-07-13T09:19:10Z",
    "url": "https://github.com/dahalujwal1000/new_practice",
    "homepage": "",
    "readMe": "just a test page"
  },
  {
    "name": "Practice-06-11",
    "description": "",
    "topics": [],
    "language": "HTML",
    "stars": 0,
    "pushedAt": "2026-07-11T17:07:11Z",
    "url": "https://github.com/dahalujwal1000/Practice-06-11",
    "homepage": "",
    "readMe": "this is trial website created with free ai tools."
  }
];

export const githubSyncedAt = "2026-09-04T12:53:43.133Z";
