// GENERATED by scripts/sync-github.mjs — do not edit by hand.
// Regenerate anytime: npm run sync (also runs automatically before every build).
// Data: public GitHub repos for dahalujwal1000 (forks & archived skipped).

export type GithubRepo = {
  name: string;
  description: string;
  topics: string[];
  language: string;
  stars: number;
  pushedAt: string;
  url: string;
  homepage: string;
  readMe: string;
};

export const githubRepos: GithubRepo[] = [
  {
    "name": "dahalujwal1000.github.io",
    "description": "",
    "topics": [],
    "language": "",
    "stars": 0,
    "pushedAt": "2026-09-17T12:01:05Z",
    "url": "https://github.com/dahalujwal1000/dahalujwal1000.github.io",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "Digital_well-being",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-15T22:53:15Z",
    "url": "https://github.com/dahalujwal1000/Digital_well-being",
    "homepage": "",
    "readMe": "Digital Wellbeing for Windows (v1.2)\nA Digital-Wellbeing-style single Windows app:\ntoday's Active screen time, Laptop open time, Idle time, Unlocks,\nhourly activity chart, top apps/websites, laptop sessions timeline —\ntracked by a background engine that lives in the system tray, viewed in a\npolished dashboard with animated ring, hover tooltips, click-to-jump week\nchart and pull-to-refresh. Restart-proof by design.\nv1 scope: tracking + storage + dashboard UI. NO blocking / task-kill.\nStack\nPython 3.11+ · CustomTkinter · SQLite · Win32 API via ctypes · PyInstaller\nRun from source (dev)\npowershell\n1. Install Python 3.11+ (winget install Python.Python.3.12) if needed\n2. From this folder:\npip install -r requirements.txt\npython runapp.py # tracker + tray (normal use)\npython runapp.py --dashboard # dashboard window\npython smoketest.py # opens the UI, auto-closes\nThe ONE executable\nThe whole product ships as a single exe:\n Command What it does \n------\n DigitalWellbeing.exe tracker + system tray (normal use / autostart) \n DigitalWellbeing.exe --dashboard open the dashboard window \n DigitalWellbeing.exe --no-tray headless tracker (testing) \nTray menu: Open Dashboard · Today's active time · …"
  },
  {
    "name": "Research_Agent",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-09T18:45:21Z",
    "url": "https://github.com/dahalujwal1000/Research_Agent",
    "homepage": "",
    "readMe": "ResearchAgent\nAI Research Agent — topic in, structured markdown report out.\nPipeline\nTopic → LLM generates 3 queries → Tavily search (5 URLs each)\n→ requests + trafilatura crawl → per-source LLM summary → final report\nSetup\npowershell\npip install -r requirements.txt\ncopy .env.example .env # then fill OPENROUTERAPIKEY + TAVILYAPIKEY\nUsage\npowershell\npython main.py \"benefits of drinking green tea\"\nreport saved to reports/ - .md\nGlobal install (call from anywhere)\npowershell\npip install -e .\nresearch-agent \"benefits of drinking green tea\"\nThis creates a research-agent command on PATH. Reports still save to the\nproject's reports/ folder, and API keys are always read from the project's\n.env no matter which folder you run from.\nFiles\n- main.py — CLI (thin, imports agent.run so API/UI can reuse later)\n- agent.py — orchestrator\n- config.py — env keys + tunables\n- search.py — Tavily client\n- crawler.py — requests + trafilatura\n- llm.py — OpenRouter client with per-stage free models:\n - queries → nvidia/nemotron-3-ultra-550b-a55b:free (reasoning)\n - summaries → google/gemma-4-31b-it:free (fast extraction)\n - report → thinkingmachines/inkling:free (long-form writing)\n - poolside …"
  },
  {
    "name": "QAgent",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-09T16:38:58Z",
    "url": "https://github.com/dahalujwal1000/QAgent",
    "homepage": "",
    "readMe": "AI Security & QA Agent\nScans a codebase or website for security vulnerabilities, vulnerable\ndependencies, broken links, and failing tests — then ranks everything by\nseverity and explains it in plain English.\nCore principle: the LLM orchestrates, it never scans. Every check is a real\nexternal tool run via subprocess; the LLM (via OpenRouter) decides which tools\nto run, reads the raw output, dedupes false positives, and writes the report.\nWhat it checks\n Check Tool (wrapped, not reinvented) \n------\n Security issues (secrets, SQLi, XSS, shell=True, weak hashing) bandit \n Vulnerable dependencies pip-audit (Python) / npm audit (Node) \n Broken links (404 / 5xx / timeouts / redirects) built-in crawler (requests) \n Test suite pass/fail pytest (junit-xml) / npm test \nSetup\nbash\npip install -r requirements.txt\npip install bandit pip-audit # scanner CLIs\ncopy .env.example .env # then add your OpenRouter key\n.env:\nOPENROUTERAPIKEY=sk-or-...\nOPENROUTERMODEL=deepseek/deepseek-chat # any OpenRouter model\nUsage\nbash\npython cli.py path/to/repo # local project\npython cli.py https://github.com/u/r.git # remote repo (cloned to temp)\npython cli.py https://example.com # website (link crawl)\npython …"
  },
  {
    "name": "My_Portfolio",
    "description": "",
    "topics": [],
    "language": "TypeScript",
    "stars": 0,
    "pushedAt": "2026-09-09T16:20:29Z",
    "url": "https://github.com/dahalujwal1000/My_Portfolio",
    "homepage": "",
    "readMe": "My Portfolio\nStack\n- React 18 + TypeScript + Vite\n- Plain CSS (CSS custom properties) — no UI framework\n- Google Fonts → JetBrains Mono\n- Deploy target: Vercel (static, free)\nQuick start\nbash\nnpm install\nnpm run dev # local dev → http://localhost:5173\nnpm run sync # refresh GitHub data into src/github.gen.ts\nnpm run build # sync + type-check + production build (dist/)\nnpm run preview # preview the production build\nCustomize\nAll site content (name, links, projects, terminal answers) lives in a single file:\nsrc/content.ts <- edit everything here\nProjects & the chatbot are fed from GitHub automatically. npm run sync\n(also runs before every build) harvests your public repos — description,\ntopics, language, stars, README digest — into src/github.gen.ts. Anything\nfound there shows up on the site and becomes chatbot knowledge. Hand-listed\nprojects in content.ts can claim a repo via repo: \"owner/name\" (stats +\nREADME flow in, no double-listing), hide unwanted repos via github.hide,\nand rewrite anything the machine got wrong — your words always win.\nProject structure\nsrc/\n content.ts <- edit everything here\n github.gen.ts <- GENERATED from GitHub (npm run sync)\n App.tsx <- hash router (#/ …"
  },
  {
    "name": "StudyMate-AI-Platform",
    "description": "AI academic assistant. Student uploads notes/syllabus/PDFs, tool answers questions, quizzes them, tracks progress, maybe schedules study. Core loop: ingest content → understand → help student (Q&A, summarize, quiz, plan).",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-06T09:31:09Z",
    "url": "https://github.com/dahalujwal1000/StudyMate-AI-Platform",
    "homepage": "",
    "readMe": "StudyMate AI 🎓\nAI academic assistant for your final year project: upload notes/syllabus/PDFs, get\nsummaries, ask grounded questions with citations, generate quizzes & flashcards,\nplan study tasks and track progress.\nCore loop\nIngest → Understand → Practice → Improve\n Feature How it works \n------\n 📄 Doc upload + summary PDF / PPTX / DOCX / TXT / MD parsed, chunked, summarized (Gemini free tier, or extractive fallback) \n 💬 RAG chatbot TF-IDF retrieval over document chunks → LLM answers with [n] citations, or grounded excerpt fallback \n 🧠 Quiz & flashcards LLM-generated MCQs + flip flashcards, score tracking per attempt \n 🗓️ Study planner Tasks with course, due date, type; todo/done toggle \n 📈 Progress dashboard Topic mastery bars, weak-topic highlight, score history chart \nTech stack\n- Backend: FastAPI + Jinja2 templates + Tailwind (CDN) — design tokens ported 1:1 from the Stitch design system\n- DB: SQLite via SQLAlchemy (swap to Postgres via DATABASEURL)\n- LLM: Gemini, Mistral, or Groq (free tiers) with automatic fallback — set the primary via LLMPROVIDER; any other provider with a key becomes a backup\n- Retrieval: in-memory TF-IDF index (stdlib) — swap for Chroma/FAISS …"
  },
  {
    "name": "URL_Shortner",
    "description": "",
    "topics": [],
    "language": "JavaScript",
    "stars": 1,
    "pushedAt": "2026-09-05T18:51:33Z",
    "url": "https://github.com/dahalujwal1000/URL_Shortner",
    "homepage": "",
    "readMe": "🔗 URL Shortener\nA full-stack URL shortener with a Node.js/Express + SQLite backend and a React (Vite + Tailwind CSS) frontend. Shorten long URLs, use custom aliases, set expiry dates, and track real-time click analytics.\n✨ Features\n- Shorten URLs — instantly generate compact short codes (Base62)\n- Custom aliases — optional user-defined short codes (3–20 alphanumeric chars)\n- Link expiration — optional expiry date per link\n- Click analytics — total clicks, referrers, user agents, and recent click activity\n- Rate limiting — 100 requests / 15 min per IP\n- Input validation — strict URL validation with the validator library\n🏗️ Tech Stack\n Layer Technology \n -------- --------------------------------------- \n Backend Node.js, Express, SQLite (sqlite3) \n Frontend React 19, Vite, Tailwind CSS, React Router \n Testing Jest + Supertest \n DevOps Docker + docker-compose, nginx \n📁 Project Structure\nURL-Shortner/\n├── backend/\n│ ├── server.js # Express entry point\n│ ├── config/database.js # SQLite connection + schema\n│ ├── controllers/ # Request handlers\n│ ├── routes/ # API + redirect routes\n│ ├── models/ # DB queries\n│ ├── services/ # Short-code generation\n│ ├── middleware/ # URL validation\n│ …"
  },
  {
    "name": "norvic-hospital",
    "description": "a hospital website with full froentend and backend",
    "topics": [],
    "language": "JavaScript",
    "stars": 2,
    "pushedAt": "2026-09-04T09:00:24Z",
    "url": "https://github.com/dahalujwal1000/norvic-hospital",
    "homepage": "",
    "readMe": "Norvic Hospital Website\nThis is a React + Vite template for the Norvic International Hospital website.\nProject Structure\n- src/components – Reusable components (Navbar, Footer, etc.)\n- src/pages – Page components (HomePage, AboutPage, ServicesPage, DoctorsPage, ContactPage)\n- src/css – Global styles and design tokens\n- public – Static assets\nFooter Design\nThe footer matches the homepage’s clean, light‑theme look while providing essential hospital information in a clear three‑column layout.\nLayout (desktop → tablet → mobile)\n1. Quick Links – Navigation to all main site pages plus Emergency, International Patients, Health Packages, Medical Insurance, Patient Portal.\n2. Contact Information – Address, phone, email, 24/7 Emergency line, with icons and social‑media links.\n3. Subscribe for Updates – Simple email signup form for health tips and hospital news.\nBelow the columns is a dark‑topped copyright bar with the year and site link.\nVisual Consistency\n- Uses the same CSS variables (--color-bg-secondary, --color-text-primary, --color-primary, etc.) and utility‑class spacing (px-4 sm:px-6 lg:px-8, space-y-, grid, flex) as the rest of the site.\n- Links, icons, and buttons have hover/focus …"
  },
  {
    "name": "Notes_SaaS",
    "description": "",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-09-03T17:25:17Z",
    "url": "https://github.com/dahalujwal1000/Notes_SaaS",
    "homepage": "",
    "readMe": "Notes SaaS API\nA production-style Notes CRUD backend with JWT authentication — built as a portfolio project to demonstrate real backend skills: auth, relational DB design, REST design, and security fundamentals.\n 🔗 Live app: https://notes-saas-001-final.onrender.com — the full Notion-style UI, deployed on Render (free tier; the first request after 15 min of inactivity may take 50 s while the service wakes up). API reference: /docs.\nFeatures\n- AI assistant (new) — a sidebar chat (\"Agents & tools → AI Assistant\") powered by a free LLM (Google Gemini, Groq or Mistral, no credit card; an offline mock assistant runs when no key is configured). It can read your tasks/notes/events and create, move, rename and delete via tool calling — the LLM never touches the database, every call is validated and scoped to your account, deletes require an explicit Confirm/Cancel step, all actions are audited (aiactions table), and chat is rate-limited per user. Config: AIPROVIDER / AIAPIKEY / MISTRALAPIKEY / AIMODEL / AIENABLED in .env — see .env.example.\n- SaaS workspace dashboard (new) — collapsible #FAFAFA sidebar with Upcoming events (add events with name/description/date; shows title, date + …"
  },
  {
    "name": "Project_zero_delay",
    "description": "",
    "topics": [],
    "language": "JavaScript",
    "stars": 0,
    "pushedAt": "2026-09-01T17:56:47Z",
    "url": "https://github.com/dahalujwal1000/Project_zero_delay",
    "homepage": "",
    "readMe": "Nepal Gamer Voice Chat\nA lightweight, low-latency voice chat application designed specifically for Nepal gamers to beat Discord in performance and accessibility.\n🔄 Recent Updates\n- Server port auto-discovery. The signaling server scans upward from its preferred port (default 3000) and writes the chosen port to server/.resolved-port. The frontend calls GET /port to learn which port to connect to. No more EADDRINUSE crashes when another process is squatting on the default.\n- Static frontend dev server. npm run frontend (or npm run dev) serves src/ on port 5173 (or the next free port). The Tauri wrapper is still supported but no longer required for local development.\n- Authentication flow. registerEmail accepts a username and writes a users/{uid} doc to Firestore. The UI reads it back so the bottom-bar username is the chosen name, not an email prefix.\n- Icon set. Replaced the Font Awesome kit placeholder (which was 403ing) with inline SVG icons for mic / headphones / cog / close.\n- Loading overlay. Clears as soon as app.js parses, so Firebase init errors don't strand the user on a spinner.\n🎯 Features\n- Ultra-low latency voice chat ( /port → {\"port\": }\nGET http://localhost: /health …"
  },
  {
    "name": "-nepal-gamer-voice_ZERO_DELAY",
    "description": " lightweight, low-latency voice chat application designed specifically for Nepal gamers to beat Discord in performance and accessibility.",
    "topics": [],
    "language": "",
    "stars": 0,
    "pushedAt": "2026-08-01T22:04:54Z",
    "url": "https://github.com/dahalujwal1000/-nepal-gamer-voice_ZERO_DELAY",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "Wheather_mobile_app",
    "description": "",
    "topics": [],
    "language": "Dart",
    "stars": 0,
    "pushedAt": "2026-08-01T04:28:12Z",
    "url": "https://github.com/dahalujwal1000/Wheather_mobile_app",
    "homepage": "",
    "readMe": "Wheathermobileapp\nWheathermobileapp"
  },
  {
    "name": "Wheather_App",
    "description": "A real time wheather showing with api ",
    "topics": [],
    "language": "Python",
    "stars": 0,
    "pushedAt": "2026-07-24T08:24:58Z",
    "url": "https://github.com/dahalujwal1000/Wheather_App",
    "homepage": "",
    "readMe": "Weather App - Django Project\nA simple weather application built with Django that fetches real-time weather data from the OpenWeatherMap API.\nFeatures\n- Current weather information for any city\n- Temperature, humidity, pressure, and wind speed\n- Weather description and icon\n- Responsive design that works on mobile and desktop\n- Clean and modern UI with CSS animations\n- Error handling for invalid cities or API issues\n- Built with Django backend and vanilla JavaScript frontend\nSetup Instructions\n1. Clone or download this repository\n2. Install dependencies\nbash\npip install -r requirements.txt\n3. Get an API key from OpenWeatherMap\n- Go to OpenWeatherMap\n- Sign up for a free account\n- Get your API key from the API keys section\n4. Create a .env file\nCreate a .env file in the project root directory (same folder as manage.py) with the following content:\nOPENWEATHERAPIKEY=youractualapikeyhere\nReplace youractualapikeyhere with the actual API key you obtained from OpenWeatherMap.\n5. Run the development server\nbash\npython manage.py runserver\n6. Visit the application\nOpen your web browser and go to: http://127.0.0.1:8000/\nHow to Use\n1. Enter a city name in the input field (default is London)\n2. …"
  },
  {
    "name": "portfolio",
    "description": "",
    "topics": [],
    "language": "TypeScript",
    "stars": 0,
    "pushedAt": "2026-07-22T10:58:39Z",
    "url": "https://github.com/dahalujwal1000/portfolio",
    "homepage": "",
    "readMe": "React + Vite\nThis template provides a minimal setup to get React working in Vite with HMR and some Oxlint rules.\nCurrently, two official plugins are available:\n- @vitejs/plugin-react uses Oxc\n- @vitejs/plugin-react-swc uses SWC\nReact Compiler\nThe React Compiler is not enabled on this template because of its impact on dev & build performances. To add it, see this documentation.\nExpanding the Oxlint configuration\nIf you are developing a production application, we recommend using TypeScript with type-aware lint rules enabled. Check out the TS template for information on how to integrate TypeScript and Oxlint's TypeScript related rules in your project."
  },
  {
    "name": "dahalujwal1000",
    "description": "",
    "topics": [],
    "language": "",
    "stars": 1,
    "pushedAt": "2026-07-18T10:51:06Z",
    "url": "https://github.com/dahalujwal1000/dahalujwal1000",
    "homepage": "",
    "readMe": "💫 About Me:\nDesigning wireframing Froentend HTML CSS JS\n🌐 Socials:\n \n💻 Tech Stack:\n \n📊 GitHub Stats:\n \n \n \n---"
  },
  {
    "name": "E-commerce",
    "description": "",
    "topics": [],
    "language": "HTML",
    "stars": 0,
    "pushedAt": "2026-07-18T02:50:26Z",
    "url": "https://github.com/dahalujwal1000/E-commerce",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "College-Website",
    "description": "",
    "topics": [],
    "language": "HTML",
    "stars": 0,
    "pushedAt": "2026-07-18T01:55:59Z",
    "url": "https://github.com/dahalujwal1000/College-Website",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "hckathon_practice",
    "description": "",
    "topics": [],
    "language": "",
    "stars": 0,
    "pushedAt": "2026-07-16T05:37:18Z",
    "url": "https://github.com/dahalujwal1000/hckathon_practice",
    "homepage": "",
    "readMe": ""
  },
  {
    "name": "new_practice",
    "description": "",
    "topics": [],
    "language": "CSS",
    "stars": 0,
    "pushedAt": "2026-07-13T09:19:10Z",
    "url": "https://github.com/dahalujwal1000/new_practice",
    "homepage": "",
    "readMe": "just a test page"
  }
];

export const githubSyncedAt = "2026-09-17T12:02:26.244Z";
